name: Auto label and assign pull requests

permissions:
  pull-requests: write
  contents: read
      
on: [pull_request]

jobs:

  auto-label-assign:
    uses: MicrosoftDocs/OfficeDocs-NotInBuild-pr/.github/workflows/AutoLabelAssign.yml@workflow-prod
    with:
      PayloadJson: ${{ toJSON(github) }}
      AutoAssignUsers: 1
      AutoLabel: 1
      ExcludedUserList: '["user1", "user2"]'
      ExcludedBranchList: '["branch1", "branch2"]'
    secrets:
      AccessToken: ${{ secrets.GITHUB_TOKEN }}


  
